# Characteristic scales for non-dimensionalization
# Optimized for O(1) values in trajectory optimization
length:
  L_ref: 1e4                 # Reference length [m] = 10 km

time:
  T_ref: 50.0                # Reference time [s]

mass:
  M_ref: 50.0                # Reference mass [kg]

velocity:
  V_ref: 1e3                 # Reference velocity [m/s] = 1000 m/s

force:
  F_ref: 5e3                 # Reference force [N] = 5000 N

pressure:
  P_ref: 1e4                 # Reference pressure [Pa] = 10 kPa

density:
  RHO_ref: 1.225             # Reference density [kg/mÂ³]
